### PR TITLE
Added Plymouth support

### LINKED ISSUE #19: [Feature Suggestion] Plymouth Support
Plymouth is a tool used to display the initial bootstages better. 
You can [read more about it here.](https://wiki.archlinux.org/index.php/Plymouth)

It however, requires the Encrypt hook to be replaced with Plymouth-encrypt.
Since YKFDE replaces the encrypt module as well, I was wondering if you could make a plymouth compatible version.

### PR DESCRIPTION
**Pull request by benruijl**
Fixes #19

### CODE REVIEW

**Comment by benruijl** [comment]
Somehow the text is not displaying under the password prompt. I have no idea why.

**Comment by edward-p** [comment]
@benruijl 

You just forgot the install script at `src/install/ykfde`

Try this patch: (It works, at least for me.)

``` diff
--- src/install/ykfde       2019-04-29 01:06:04.343333558 +0800
+++ src/install/ykfde       2019-04-29 00:54:04.629999960 +0800
@@ -43,6 +43,13 @@
   add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
   add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
 
+  # plymouth on-screen text needed
+  add_binary "/usr/lib/plymouth/label.so"
+  add_binary "/usr/lib/plymouth/text.so"
+  add_file "/usr/share/fonts/TTF/DejaVuSans.ttf"
+  add_file "/etc/fonts/fonts.conf"
+  add_file "/etc/fonts/conf.d/60-latin.conf"
+  
   # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
   add_binary "/usr/lib/libgcc_s.so.1"
```

**Comment by edward-p** [comment]
> @benruijl
> 
> You just forgot the install script at `src/install/ykfde`
> 
> Try this patch: (It works, at least for me.)
> 
> ```diff
> --- src/install/ykfde       2019-04-29 01:06:04.343333558 +0800
> +++ src/install/ykfde       2019-04-29 00:54:04.629999960 +0800
> @@ -43,6 +43,13 @@
>    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
>    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
>  
> +  # plymouth on-screen text needed
> +  add_binary "/usr/lib/plymouth/label.so"
> +  add_binary "/usr/lib/plymouth/text.so"
> +  add_file "/usr/share/fonts/TTF/DejaVuSans.ttf"
> +  add_file "/etc/fonts/fonts.conf"
> +  add_file "/etc/fonts/conf.d/60-latin.conf"
> +  
>    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
>    add_binary "/usr/lib/libgcc_s.so.1"
> ```

However, it will fail the `mkinitcpio`, if `plymouth` is not installed.

We need add an if statement, or create a new hook like:

*  `src/hook/ykfde-plymouth`
*  `src/install/ykfde-plymouth`

**Comment by benruijl** [comment]
I think an if-statement if nicer, to prevent having two almost identical hook files.

**Comment by edward-p** [comment]
> I think an if-statement if nicer, to prevent having two almost identical hook files.

Agree. Since we can always use `ESC` to fallback to console mode.

**Comment by Vincent43** [comment]
@benruijl I merged your PR alongside some improvements in https://github.com/agherzan/yubikey-full-disk-encryption/commit/aacf45583bffd7034adc665b3ec90084051ed03c. Thank you for contribution.

**Pull request merged**
