### PR TITLE
Merge pull request for extending README.md

### PR DESCRIPTION
**Pull request by TheRojam**
Added Information 4 installatio from AUR.
See also Issue conversations #39

### CODE REVIEW

**Comment by TheRojam** [comment]
@agherzan @Vincent43 could you please review and merge?

**Comment by agherzan** [comment]
Thanks @TheRojam

**Comment by Vincent43** [comment]
@TheRojam You still didn't fixed [PKGBUILD](https://aur.archlinux.org/packages/yubikey-full-disk-encryption-git/) which [I told you about](https://github.com/agherzan/yubikey-full-disk-encryption/issues/39#issuecomment-456552328). That makes your AUR package broken so we obviously can't recommend to install it here.

Also please keep **Table of contents** in sync with your changes.

I'm sorry but I have to revert this for now.

**Comment by agherzan** [comment]
@Vincent43 I see. Thanks for handling this.

**Comment by Vincent43** [comment]
@TheRojam I added link toy your package in [README](https://github.com/agherzan/yubikey-full-disk-encryption#from-aur), thank you.

**Pull request merged**
